<a href="https://colab.research.google.com/github/MuqeetBuilds/Data-Science-Portfolio/blob/main/01_Flight_Price_Regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import pandas as pd
import numpy as np
import random
np.random.seed(42)
random.seed(42)

In [11]:
airlines = ['Vistara', 'Air India', 'Indigo', 'SpiceJet', 'GoFirst']
cities = ['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai']
times = ['Morning', 'Afternoon', 'Evening', 'Night']

In [12]:
data = {
    'Airline': [random.choice(airlines) for _ in range(5000)],
    'Source_City': [random.choice(cities) for _ in range(5000)],
    'Destination_City': [random.choice(cities) for _ in range(5000)],
    'Departure_Time': [random.choice(times) for _ in range(5000)],
    'Days_Left': np.random.randint(1, 50, size=5000), # Days left until the flight
    'Duration_Hours': np.round(np.random.uniform(2.0, 15.0, size=5000), 1)
}

In [13]:
df = pd.DataFrame(data)
df.head()

,Airline,Source_City,Destination_City,Departure_Time,Days_Left,Duration_Hours
0,Vistara,Delhi,Delhi,Night,39,8.3
1,Vistara,Mumbai,Delhi,Night,29,6.3
2,Indigo,Kolkata,Delhi,Morning,15,12.3
3,Air India,Chennai,Delhi,Evening,43,7.9
4,Air India,Hyderabad,Kolkata,Morning,8,4.4

In [14]:
df.loc[df['Source_City'] == df['Destination_City'],'Destination_City']='chennai'

In [17]:
base_price = 3000
airline_multiplier = df['Airline'].map({'Vistara':3000,'Air India':2000,'Indigo':0,'SpiceJet':-500,'GoFirst':-500})
time_penalty = df['Days_Left'].apply(lambda x:5000 if x<5 else (2000 if x<15 else 0 ))
duration_cost = df['Duration_Hours']*500
df["price"] = base_price + airline_multiplier + time_penalty +duration_cost +np.random.randint(-1000,1000,size =5000)
print ("data successfully loaded")

data successfully loaded

In [19]:
df.head()
df.describe()

         Days_Left  Duration_Hours         price
count  5000.000000      5000.00000   5000.000000
mean     25.232400         8.39736   8797.432600
std      14.138004         3.73935   2841.178685
min       1.000000         2.00000   2645.000000
25%      13.000000         5.10000   6680.250000
50%      25.000000         8.30000   8677.000000
75%      37.000000        11.60000  10619.000000
max      49.000000        15.00000  18968.000000

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Airline           5000 non-null   object
 1   Source_City       5000 non-null   object
 2   Destination_City  5000 non-null   object
 3   Departure_Time    5000 non-null   object
 4   Days_Left         5000 non-null   int64
 5   Duration_Hours    5000 non-null   float64
 6   price             5000 non-null   float64
dtypes: float64(2), int64(1), object(4)
memory usage: 273.6+ KB

In [21]:
df.head()

,Airline,Source_City,Destination_City,Departure_Time,Days_Left,Duration_Hours,price
0,Vistara,Delhi,chennai,Night,39,8.3,9244.0
1,Vistara,Mumbai,Delhi,Night,29,6.3,8934.0
2,Indigo,Kolkata,Delhi,Morning,15,12.3,8798.0
3,Air India,Chennai,Delhi,Evening,43,7.9,9722.0
4,Air India,Hyderabad,Kolkata,Morning,8,4.4,8552.0

In [22]:
print(df.shape)

(5000, 7)

In [23]:
df.shape

(5000, 7)

In [24]:
df.head()

,Airline,Source_City,Destination_City,Departure_Time,Days_Left,Duration_Hours,price
0,Vistara,Delhi,chennai,Night,39,8.3,9244.0
1,Vistara,Mumbai,Delhi,Night,29,6.3,8934.0
2,Indigo,Kolkata,Delhi,Morning,15,12.3,8798.0
3,Air India,Chennai,Delhi,Evening,43,7.9,9722.0
4,Air India,Hyderabad,Kolkata,Morning,8,4.4,8552.0

In [25]:
#fearure engineering
df_encoding = pd.get_dummies(df,columns = ['Airline','Source_City','Destination_City','Departure_Time'])
print(f"old shape{df.shape}")
print(f"new shape{df_encoding.shape}")

old shape(5000, 7)
new shape(5000, 25)

In [26]:
df.shape

(5000, 7)

In [27]:
df.head()

,Airline,Source_City,Destination_City,Departure_Time,Days_Left,Duration_Hours,price
0,Vistara,Delhi,chennai,Night,39,8.3,9244.0
1,Vistara,Mumbai,Delhi,Night,29,6.3,8934.0
2,Indigo,Kolkata,Delhi,Morning,15,12.3,8798.0
3,Air India,Chennai,Delhi,Evening,43,7.9,9722.0
4,Air India,Hyderabad,Kolkata,Morning,8,4.4,8552.0

In [29]:
df_encoding.head()

,Days_Left,Duration_Hours,price,Airline_Air India,Airline_GoFirst,Airline_Indigo,Airline_SpiceJet,Airline_Vistara,Source_City_Bangalore,Source_City_Chennai,...,Destination_City_Chennai,Destination_City_Delhi,Destination_City_Hyderabad,Destination_City_Kolkata,Destination_City_Mumbai,Destination_City_chennai,Departure_Time_Afternoon,Departure_Time_Evening,Departure_Time_Morning,Departure_Time_Night
0,39,8.3,9244.0,False,False,False,False,True,False,False,...,False,False,False,False,False,True,False,False,False,True
1,29,6.3,8934.0,False,False,False,False,True,False,False,...,False,True,False,False,False,False,False,False,False,True
2,15,12.3,8798.0,False,False,True,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
3,43,7.9,9722.0,True,False,False,False,False,False,True,...,False,True,False,False,False,False,False,True,False,False
4,8,4.4,8552.0,True,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False

In [30]:
x=df_encoding.drop('price',axis =1)
y=df_encoding['price']

In [31]:
x

,Days_Left,Duration_Hours,Airline_Air India,Airline_GoFirst,Airline_Indigo,Airline_SpiceJet,Airline_Vistara,Source_City_Bangalore,Source_City_Chennai,Source_City_Delhi,...,Destination_City_Chennai,Destination_City_Delhi,Destination_City_Hyderabad,Destination_City_Kolkata,Destination_City_Mumbai,Destination_City_chennai,Departure_Time_Afternoon,Departure_Time_Evening,Departure_Time_Morning,Departure_Time_Night
0,39,8.3,False,False,False,False,True,False,False,True,...,False,False,False,False,False,True,False,False,False,True
1,29,6.3,False,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,False,True
2,15,12.3,False,False,True,False,False,False,False,False,...,False,True,False,False,False,False,False,False,True,False
3,43,7.9,True,False,False,False,False,False,True,False,...,False,True,False,False,False,False,False,True,False,False
4,8,4.4,True,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4995,1,2.9,False,False,False,True,False,False,False,False,...,False,False,True,False,False,False,False,False,False,True
4996,29,9.7,True,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,False,False,True
4997,22,8.8,False,False,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,True
4998,16,11.6,False,False,False,True,False,False,False,False,...,True,False,False,False,False,False,True,False,False,False
4999,41,8.6,False,False,True,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False

In [32]:
y

0        9244.0
1        8934.0
2        8798.0
3        9722.0
4        8552.0
         ...
4995     9425.0
4996    10042.0
4997     6458.0
4998     7600.0
4999     6852.0
Name: price, Length: 5000, dtype: float64

In [34]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [35]:
print("Data successfully cleaned and split!")
print(f"Training Data (Practice Test) has {x_train.shape[0]} flights.")
print(f"Testing Data (Final Exam) has {x_test.shape[0]} flights.")

Data successfully cleaned and split!
Training Data (Practice Test) has 4000 flights.
Testing Data (Final Exam) has 1000 flights.

In [36]:
df_encoding.shape

(5000, 25)

In [39]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error , r2_score
model = RandomForestRegressor(n_estimators=100,random_state=42)
print("Training the random forest ")
model.fit(x_train,y_train)
prediction = model.predict(x_test)
mae=mean_absolute_error(y_test,prediction)
r2=r2_score(y_test,prediction)

print("done!")
print(f"Mean absolute error : {mae}")
print(f"Accuracy Score : {r2}")

Training the random forest
done!
Mean absolute error : 521.9753761904763
Accuracy Score : 0.9512744053724272